sudo: required
services:
  - docker

before_install:
  - docker build ehsan1222/docker-react -f Dockerfile.dev

script:
  - docker run ehsan1222/docker-react npm run test -- --converage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: 
  bucket_path:
  on:
    branch: master
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
