FROM node:16-alpine

ENV NODE_MODULES_DIR=/usr/app/node_modules

WORKDIR /usr/app
COPY ./package.json .
RUN npm install

RUN chown node:node -R ${NODE_MODULES_DIR}
USER node
# RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
CMD [ "npm", "run", "start" ]
